### ISSUE TITLE
'show' function does not work

### ISSUE THREAD

**Issue by donmullen** [relevance/labrepl#30] opened 2010-10-08 15:28 UTC
(source show) and (doc show) both work.

However:

user=> (show Integer)
NoSuchMethodError clojure.lang.Numbers.lt(Ljava/lang/Object;I)Z  clojure.contrib.string/partition/step--78/fn--79 (string.clj:225)

user=> (show show)
NoSuchMethodError clojure.lang.Numbers.add(II)I  clojure.contrib.string/partition/step--78/fn--79 (string.clj:224)

Lab uses clojure-1.3.0-alpha1.jar and clojure-contrib-1.2.0.jar

**Comment by donmullen** [comment] 2010-10-08 17:02
Stuart Sierra suggested possibly integrating Mycroft into the labrepl, and said 'show' wasn't being actively maintained.

**Comment by abedra** [comment] 2010-10-15 13:33
This is fixed in as of 275bbf9221e98b70e16d782a6ff9d217d655a743.  The issue was caused by a conflicting clojure-1.3.0-alpha and clojure-contrib-1.2.0

**Closed as completed by abedra** 2010-10-15 13:33 UTC
Labels: defect
